### ISSUE TITLE
安卓5.1设置参数后直接退出，再打开就闪退

### ISSUE THREAD

**Issue by WODEDADIAO** [shutup/Kcptun_android#2]
安卓5.1设置参数后直接退出，再打开就闪退

**Comment by shutup** [comment]
是什么型号的手机呢？

**Comment by WODEDADIAO** [comment]
@shutup 魅族

**Comment by shutup** [comment]
具体的型号呢？另外你可以去试试shadowsocks最新的包，已经整合了kcptun.

**Comment by WODEDADIAO** [comment]
@shutup shadowsocks最新的包不支持混淆，手机是魅蓝note3

**Comment by shutup** [comment]
我已经知道闪退原因了，晚上尽量改好。你说的混淆是谁提供的功能呢？

**Comment by WODEDADIAO** [comment]
@shutup ssr

**Comment by shutup** [comment]
@WODEDADIAO 您好，您可以试一下新版本，应该解决了。

**Comment by WODEDADIAO** [comment]
@shutup 完美解决，太感谢了

**Comment by shutup** [comment]
@WODEDADIAO 不客气，是我考虑不够周全，现在代码感觉有点乱，抽时间继续优化下。

**Comment by koolwiki** [comment]
楼主这个软件非常好，没想到其他设备上都可以连上去。
